Fixing timestamp conversion bug
oxeanbits/forecast-chart pull request #9
Opened 2019-11-22 19:57 UTC by rodiguif

## Description
This PR fixes a timestamp conversion bug.

2019-11-22 20:31 UTC, niltonvasques requested changes

2019-11-22 20:31 UTC, niltonvasques commented on core/src/main/java/com/oxeanbits/forecastchart/core/util/DateFormatter.kt
> +        mDate.time = timestamp.times(1000) + ONE_DAY
Lets check if the date coming in the array will not change regardless the timezone of the user.

2019-11-23 01:39 UTC, rodiguif commented
Now, the code ensures that dates are always converted at 12AM with UTC timezone.

2019-11-25 12:56 UTC, niltonvasques requested changes

2019-11-25 12:56 UTC, niltonvasques commented on app/src/main/java/com/oxeanbits/forecastchart/ui/MainExample.kt
> +        AndroidThreeTen.init(this)
Seems that we need to include this remind in the README.

2019-11-25 13:44 UTC, merged